### ISSUE TITLE
A system for releases of the container-workflow-tool

### ISSUE THREAD

**Issue by zmiklank** [sclorg/container-workflow-tool#41]
Hello,

would it be possible to create release tagging system for the container-workflow-tool?

With marked release commits that are denoting steady state of the application is easier to create versioned packages of the tool, e.g., for some Linux distributions.

Currently I have in plan to create a container-workflow-tool package for Fedora and it would be really helpful, if I can use an upstreamed versioning from the start

**Comment by phracek** [comment]
Hi @zmiklank ,

thanks for this issue. container-workflow-tool is a base python "container library" for downstream name 'docker-rebuild-helper'.

Set some versioning is fine and it can be also used for uploading each new release into PyPi.

container-workflow-tool is used mainly by our team and bot called 'betka' https://github.com/sclorg/betka which cares about syncing upstream container changes in 'https://github.com/sclorg' into Fedora container land.

My question is, why do you want to create a package for Fedora? Is it needed?

**Comment by pkubatrh** [comment]
Some release versioning definitely makes sense to me. Let me take a look and prepare something.

**Comment by pkubatrh** [comment]
Created first release for cwt: https://github.com/sclorg/container-workflow-tool/releases/tag/1.0.0

**Comment by phracek** [comment]
@zmiklank After the discussion with @pkubatrh, I agree to create a package for Fedora. Feel free to create a PR with an updated setup.py and the rest. Add me as an assignee and I will review it.

**Comment by zmiklank** [comment]
@pkubatrh Thank you for creating the versioning system.

> My question is, why do you want to create a package for Fedora? Is it needed?

General answer would be to make this tool more accessible for Fedora users.

>@zmiklank After the discussion with @pkubatrh, I agree to create a package for Fedora. Feel free to create a PR with an updated setup.py and the rest. Add me as an assignee and I will review it.

Great! I will send the PR, when it's ready.
